import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ProfileAppProiver from "./profileContext/profileAppContext";


export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProfileAppProiver>
            <div className="space-y-10">
                <Navbar mode={'dark'} />
                {children}
                <Footer />
            </div>
        </ProfileAppProiver>
    )
}
