import ChangeImg from "@/app/components/ChangeImg";
import { Metadata } from "next";
import AccountNav from "@/app/components/AccountNav";


export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="space-y-10">
            <ChangeImg />
            <div className="flex flex-col items-center justify-center">
                <AccountNav />
                <div className="w-full">
                    {children}
                </div>
            </div>
        </div>
    )
}
